[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
 

[build.environment]
  NODE_VERSION = "18.19.1"  
  NPM_VERSION = "10.2.4"    